/*  
Create a Fibonacci sequence where the new term is generated by adding the previous two terms.  
Starting with 1, and 2, the first 10 terms will be: 

1,2,3,5,8,13,21,34,55,89,....

The Fibonacci sequence values do not exceed four million, find the sum of all the even-valued terms.
*/

var a = 1;
var b = 2;
var c = 3;
var sum = 2;

while (c < 4000000) {
  var a = b;
  var b = c;
  var c = a + b;

  if ( c % 2 === 0) {
    sum += c;
  }
}

console.log("The total sum for the problem is " + sum + ".")

